### ISSUE TITLE
Proton game doesn't use the system-provided icon

### ISSUE THREAD

**Issue by Tiagoquix** [BlueManCZ/SIF#39]
I'm playing https://store.steampowered.com/app/787480/Phoenix_Wright_Ace_Attorney_Trilogy/, which runs through Proton, but it uses its default `.exe` icon instead of the system-provided icon.

By the way, I'm using the latest version of Proton-GE, but I don't think this causes any problems related to the icons.

Thanks in advance.

**Comment by BlueManCZ** [comment]
If the game has a unique `WM_CLASS`, which in this case it does, you don't need `WM_NAME`. You just add
   
```
"787480": "steam_app_787480",
```

to the `"wm_classes"` section in the `database.json`.

However, the script should automatically detect Proton games (if you indeed selected custom Proton in the dropdown menu in games properties / compatibility). I added a custom log for this in [latest commit](https://github.com/BlueManCZ/SIF/commit/6aff46c529fa744d3eaee012b8b8e86fdfd36e0a).

Can you update and share the output of `./sif.py --verbose`? Can you share the output of `./sif.py --icons` as well?

**Comment by BlueManCZ** [comment]
Thank you for the outputs. It seems that you may have configured the Proton-GE in `Steam` > `Settings` > `Compatibility` > `Enable Steam Play for all other titles`. Am I right? This is currently not supported by the script (And I will need to update the documentation for this or somehow fix it).

What is supported tho, is if you set the Proton version for the specific game. Right-click on the game in the library > `...Properties` > `Compatibility` > `Force the use of a specific Steam Play compatibility tool`, select the Proton version and then run the SIF script again.

This is because SIF script looks for Proton-specific games in the `~/.local/share/Steam/config/config.vdf` file in the section `CompatToolMaping` and those are necessary to be configured per game.

**Comment by BlueManCZ** [comment]
If you don't want to change your Steam options, I added a new `--proton` option in [latest commit](https://github.com/BlueManCZ/SIF/commit/9482d414addc0031a7505bca77f68fbeda298857), which must be used only in combination with `--single` option. So you would fix your game with:
```
./sif.py --single 787480 --proton
```
